
### DPVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 24
REMOVAL_WINDOW: 12
OPTIMIZATION_WINDOW: 5
PATCH_LIFETIME: 6
KEYFRAME_INDEX: 3

# threshold for keyframe removal
KEYFRAME_THRESH: 20.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

CENTROID_SEL_STRAT: 'RANDOM'

# DEVO specific?
# Select between random, gradient, scorer
PATCH_SELECTOR: 'scorer'
# Normalizer (only evs): none, rescale, standard (std)
NORM: 'std'
# Eval mode of patch selector (random, topk, multinomial)
SCORER_EVAL_MODE: 'multi'
SCORER_EVAL_USE_GRID: True